"""table task hisotry added

Revision ID: 1bbfe6ed26ac
Revises: adbba2dc8b4b
Create Date: 2026-07-18 15:33:21.608436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1bbfe6ed26ac'
down_revision: Union[str, Sequence[str], None] = 'adbba2dc8b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['todo.task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='todo'
    )
    op.create_index(op.f('ix_todo_task_history_id'), 'task_history', ['id'], unique=False, schema='todo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_task_history_id'), table_name='task_history', schema='todo')
    op.drop_table('task_history', schema='todo')
    # ### end Alembic commands ###
