"""initial_schema

Revision ID: 58aa04e70cd0
Revises: 
Create Date: 2026-07-11 17:55:58.597474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '58aa04e70cd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='todo'
    )
    op.create_index(op.f('ix_todo_priority_id'), 'priority', ['id'], unique=False, schema='todo')
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='todo'
    )
    op.create_index(op.f('ix_todo_status_id'), 'status', ['id'], unique=False, schema='todo')
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='todo'
    )
    op.create_index(op.f('ix_todo_user_email'), 'user', ['email'], unique=True, schema='todo')
    op.create_index(op.f('ix_todo_user_id'), 'user', ['id'], unique=False, schema='todo')
    op.create_index(op.f('ix_todo_user_user_name'), 'user', ['user_name'], unique=True, schema='todo')
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('due_date_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['priority_id'], ['todo.priority.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['todo.status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['todo.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='todo'
    )
    op.create_index(op.f('ix_todo_task_id'), 'task', ['id'], unique=False, schema='todo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_task_id'), table_name='task', schema='todo')
    op.drop_table('task', schema='todo')
    op.drop_index(op.f('ix_todo_user_user_name'), table_name='user', schema='todo')
    op.drop_index(op.f('ix_todo_user_id'), table_name='user', schema='todo')
    op.drop_index(op.f('ix_todo_user_email'), table_name='user', schema='todo')
    op.drop_table('user', schema='todo')
    op.drop_index(op.f('ix_todo_status_id'), table_name='status', schema='todo')
    op.drop_table('status', schema='todo')
    op.drop_index(op.f('ix_todo_priority_id'), table_name='priority', schema='todo')
    op.drop_table('priority', schema='todo')
    # ### end Alembic commands ###
