"""add_tag_tables_and_field

Revision ID: adbba2dc8b4b
Revises: 58aa04e70cd0
Create Date: 2026-07-11 18:18:47.743177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'adbba2dc8b4b'
down_revision: Union[str, Sequence[str], None] = '58aa04e70cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='todo'
    )
    op.create_index(op.f('ix_todo_tag_name'), 'tag', ['name'], unique=True, schema='todo')
    op.create_table('task_tag',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['todo.tag.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['todo.task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'tag_id'),
    schema='todo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_tag', schema='todo')
    op.drop_index(op.f('ix_todo_tag_name'), table_name='tag', schema='todo')
    op.drop_table('tag', schema='todo')
    # ### end Alembic commands ###
