"""add user_id and renaming title to operation in task history table

Revision ID: be905a644a19
Revises: 1bbfe6ed26ac
Create Date: 2026-07-18 18:17:42.088876

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be905a644a19'
down_revision: Union[str, Sequence[str], None] = '1bbfe6ed26ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False), schema='todo')
    op.add_column('task_history', sa.Column('user_id', sa.Integer(), nullable=False), schema='todo')
    op.drop_column('task_history', 'title', schema='todo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False), schema='todo')
    op.drop_column('task_history', 'user_id', schema='todo')
    op.drop_column('task_history', 'operation', schema='todo')
    # ### end Alembic commands ###
